[[app]]
name = "chrome"
virtual_key = "vk_chrome"

[[app]]
name = "obsidian"
virtual_key = "vk_obsidian"

[[app]]
name = "foot"
caption = "^Zellij"
virtual_key = "vk_zellij"

[[app]]
name = "foot"
caption = "Nvim$"
virtual_key = "vk_nvim"

[[app]]
name = "konsole"
caption = "zellij — Konsole$"
virtual_key = "vk_zellij"

[[app]]
name = "konsole"
caption = "nvim — Konsole$"
virtual_key = "vk_nvim"

[[app]]
name = "foot|konsole"
virtual_key = "vk_foot"

[[app]]
name = "dolphin"
virtual_key = "vk_dolphin"


